version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: construction_backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: construction_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always